### ISSUE TITLE
ubuntu 20.04 - Problem building - URL unavailable

### ISSUE THREAD

**Issue by Schmittfinger** [crazycat69/media_build#7]
Since last update I have the following error building the media_build-project:

root@schorsch:~/media_build# ./build
Checking if the needed tools for Ubuntu 20.04.6 LTS are available
Needed package dependencies are met.

************************************************************
* This script will download the latest tarball and build it*
* Assuming that your kernel is compatible with the latest  *
* drivers. If not, you'll need to add some extra backports,*
* ./backports/<kernel> directory.                          *
* It will also update this tree to be sure that all compat *
* bits are there, to avoid compilation failures            *
************************************************************
************************************************************
* All drivers and build system are under GPLv2 License     *
* Firmware files are under the license terms found at:     *
* https://github.com/crazycat69/media_build/releases/download/latest *
* Please abort in the next 5 secs if you don't agree with  *
* the license                                              *
************************************************************

Not aborted. It means that the licence was agreed. Proceeding...

****************************
Updating the building system
****************************
remote: You may not have access to this repository or it no longer exists in this workspace. If you think this repository exists and you have access, make sure you are authenticated.
fatal: repository 'https://bitbucket.org/CrazyCat/media_build.git/' not found
make: Entering directory '/root/media_build/linux'
wget https://github.com/crazycat69/media_build/releases/download/latest/linux-media-LATEST.tar.bz2.md5 -O linux-media.tar.bz2.md5.tmp
--2023-07-28 13:23:41--  https://github.com/crazycat69/media_build/releases/download/latest/linux-media-LATEST.tar.bz2.md5
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-07-28 13:23:42 ERROR 404: Not Found.

make: *** [Makefile:178: download] Error 8
make: Leaving directory '/root/media_build/linux'
Download failed at ./build line 535
root@schorsch:~/media_build#

Can you please solve the problem with unavailable URL (https://bitbucket.org/CrazyCat/media_build.git/).

Best regards and greetings from germany
Sebastian

**Comment by crazycat69** [comment]
fixed, latest snapshot uploaded
